### ISSUE TITLE
Homekit says thermostat is not responding

### ISSUE THREAD

**Issue by EricTSten** [jeffschubert/homebridge-daikin-oneplus#1]
**Describe The Bug:**
After connecting my thermostat to Homebridge it shows up and list the current temp but the tile for it says not responding in Homekit.  Adjusting the temp appears to work.

**To Reproduce:**
Connect the thermostat to Homebridge, check Homekit for the status

**Expected behavior:**
The thermostat tile in Homekit is in a responding state.

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
[7/21/2021, 5:23:55 PM] [Daikin One+] Found 1 location(s): 
[7/21/2021, 5:23:55 PM] [Daikin One+] Location: Home
[7/21/2021, 5:23:55 PM] [Daikin One+] Found 1 device(s): 
[7/21/2021, 5:23:55 PM] [Daikin One+] Device: Home
[7/21/2021, 5:23:55 PM] [Daikin One+] Loaded initial data.
[7/21/2021, 5:23:55 PM] [Daikin One+] Found device: Hallway

No other entries

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
{
            "name": "Daikin One+",
            "user": "<email address>",
            "password": "<password>",
            "refreshInterval": 10,
            "includeDeviceName": true,
            "platform": "DaikinOnePlus"
        }
**Screenshots:**
<!-- If applicable, add screenshots to help explain your problem. -->

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 1.3.4
* **Node.js Version**: 14.16.0
* **NPM Version**: 6.14.11
* **Operating System**: Raspbain
<!-- Click the "Preview" tab before you submit to ensure the formatting is correct. -->

**Comment by jeffschubert** [comment]
@EricTSten I've seen this inconsistently not only with my plugin but other homebridge plugins. It always appears to be temporary and resolves itself shortly. I believe it is a side effect of how HomeKit queries Homebridge and its accessories and how quickly they respond. (Searching the homebridge GitHub issues, it comes up a lot for all sorts of plugins.)

If it consistently happens every time you see the tile or it requires restarting homebridge or something similar, we'll need to take a closer look.

**Comment by EricTSten** [comment]
Jeff,

   To give more detail.  The tile says not responding when I try to adjust the temp through HomeKit.  The tile goes to a not responding state and the temp doesn’t always change on the thermostat.  After a little while it will go back to an online state but only until I try to adjust the temp again. 

  I’ve restarted the Homebridge service a couple of times and it doesn’t seem to have helped. 

  This is the first plug-in that I’ve seen do this.  I’ve had a Honeywell thermostat plug-in that worked fine and I have a Ring alarm plug-in that has no issues.

  Could adjusting the refresh interval help?

     Thanks

          Eric Sten


*******************************************
No trees were killed in the sending of this message.
However a large number of electrons were terribly inconvenienced. 
*******************************************

**Comment by jeffschubert** [comment]
Thanks for the extra details. That helped me reproduce it here on mine. Lowering the refresh interval may help, but I doubt it will eliminate the issue.
I'll see if I can tweak how it sets the target temp to avoid the issue.

**Comment by EricTSten** [comment]
Jeff,

  I’m glad to help.  If there is anything else I can do: test, etc. just let me know. 

   Thanks

      Eric Sten 

*******************************************
No trees were killed in the sending of this message.
However a large number of electrons were terribly inconvenienced. 
*******************************************

**Comment by jeffschubert** [comment]
@EricTSten I just published 1.0.3 which should fix the 'No Response' you're seeing. I still need to fix it temporarily showing the old value after you change it. It'll update to the new value for good once it refreshes values via the Daikin API.

**Comment by EricTSten** [comment]
Jeff, 

  The update did fix the not responding issue perfectly, thank you!  However, it brought to light another apparent issue.  If the thermostat is set to a schedule it over-rides/prevents any changes made in HomeKit.  

	Thanks

	   Eric

**Comment by jeffschubert** [comment]
That's odd. If you can provide any more details, add them to the issue I created for it. 
Thanks!
