### ISSUE TITLE
Support Thermostat Range View in HomeKit

### ISSUE THREAD

**Issue by prsng** [jeffschubert/homebridge-daikin-oneplus#11]
@jeffschubert 
Just an idea I have seen implemented on scrypted - 
[Link to commit](https://github.com/koush/scrypted/commit/9a52c99eb83fd873b35049f3b645b92cf75cea1f)

This adds a tick on the upper range of the value coming from thermostats that support auto heat/cool and auto range. You might want to connect to the discord from scrypted, and you'll see it there in development channel there. A screenshot below for auto range setup, and the heat  #mode
<img width="379" alt="Screen Shot 2021-11-16 at 11 03 07 PM" src="https://user-images.githubusercontent.com/12123395/142143698-46602cbe-b136-4454-b9dd-90b88571e463.png">
<img width="353" alt="Screen Shot 2021-11-16 at 11 04 34 PM" src="https://user-images.githubusercontent.com/12123395/142143856-0c7a6138-2ef7-4854-af21-8b75a8548bbb.png">

**Comment by jeffschubert** [comment]
Thanks, I'll take a look and see if I can add it at some point.
