### ISSUE TITLE
Duplicate Serial Numbers for All Accessories

### ISSUE THREAD

**Issue by prsng** [jeffschubert/homebridge-daikin-oneplus#23]
This issue does not point to any existing problem.
I love the fact that I now have the thermostat and other accessories in HomeKit.

I downloaded Controller for Homekit app to validate issues, and the app, as a best practice recommends that Homebridge accessories (all exposed from this plugin) have duplicate serial numbers.

No alternatives are required thus far as everything works pretty well currently but I thought I would raise this so that you could look at this.

![IMG_3C22CF3CD81D-1](https://user-images.githubusercontent.com/12123395/173388357-eba1a7b0-741a-4738-955b-d6a1c3fa7776.jpeg)

**Comment by jeffschubert** [comment]
Thanks, I read up on this last year and I attempted to have unique serials starting off with the initial thermostat accessory. But as I exposed the fan/sensors/etc as separate accessories, I didn't realize they were all using the same uuid/serial.
The biggest hurdle at this point is how to avoid changing the serial for existing accessories but make new accessories with unique serials. While HomeKit allows duplicate serials, it does require serial numbers to never change once the accessory is added.
