### ISSUE TITLE
3.1.0 has strange behavior with Away Mode

### ISSUE THREAD

**Issue by bverenkoff** [jeffschubert/homebridge-daikin-oneplus#27]
Since upgrading to 3.1.0, whenever I use HomeKit to set my Daikin to "Away" mode (either manually or via automation), when I turn "Away" mode back off, it automatically turns the Daikin Schedule mode to "On". This occurs whether or not I'm using the Switch to enable the Schedule toggle.

This is not desired behavior. This behavior doesn't exist if you enable and then disable Away mode using the Daikin app or directly on the thermostat. It also does not occur on version 3.0.0, this is definitely related to 3.1.0.

**Comment by jeffschubert** [comment]
Ahh, yes, you're right. 3.1 attempts to resume the schedule automatically only if one is defined. But it looks like I need to revisit how it detects an existing schedule. Looking closer at it, I think the Daikin data would always indicate a schedule existed, even if you've never adjusted it yourself.

I'll see what I can do. If nothing else, I'll add another setting to auto-enable the schedule when returning from Away and default it to off to return to the previous behavior.

**Comment by bverenkoff** [comment]
Thanks for the quick response. The Daikin always has a schedule, you cannot delete the last schedule entry. So “On” and “Off” are really important as you cannot have no schedule.

By default, Daikin does not “resume” schedules after coming off Away. If a schedule is already on, it’ll resume, but if Schedule is off, it simply just turns Away off.

Thanks for looking into it. I down rev’d to 3.0.0 which works fine as I don’t use schedules but heavily rely on Away.

Cheers!

Sent from my iPhone

On Oct 29, 2022, at 20:20, jeffschubert ***@***.***> wrote:

﻿

Ahh, yes, you're right. 3.1 attempts to resume the schedule automatically only if one is defined. But it looks like I need to revisit how it detects an existing schedule. Looking closer at it, I think the Daikin data would always indicate a schedule existed, even if you've never adjusted it yourself.

I'll see what I can do. If nothing else, I'll add another setting to auto-enable the schedule when returning from Away and default it to off to return to the previous behavior.

**Comment by jeffschubert** [comment]
Thanks again for bringing this to my attention. I've published 3.1.1 which adds a new setting to optionally enable the schedule after returning from away. It reverts the default behavior to pre-3.1.0 and doesn't enable the schedule in that case unless the setting is also enabled.

**Comment by bverenkoff** [comment]
Thanks for the quick turn around. I just put 3.1.1 in and it works fine. I see the switch, but I’m not using it. Thanks for the quick work!

Cheers,
Brian

On Oct 29, 2022, at 21:19, jeffschubert ***@***.***> wrote:



Thanks again for bringing this to my attention. I've published 3.1.1 which adds a new setting to optionally enable the schedule after returning from away. It reverts the default behavior to pre-3.1.0 and doesn't enable the schedule in that case unless the setting is also enabled.
