### ISSUE TITLE
Home Kit Automations not kicking off Thermostat

### ISSUE THREAD

**Issue by Githubnewbynewb** [jeffschubert/homebridge-daikin-oneplus#28]
**Describe The Bug:**
I create automations for my thermostat after installing the plugin and they are seemingly ignored by the plugin/HomeKit.

**To Reproduce:**
For me, I cannot get the thermostat to recognize setting the thermostat to a warmer or cooler temp at a specified time OR with the other parameters Apple allows you to input for a trigger.

**Expected behavior:**
Expect that when I set the automation up properly it will run and the thermostat will change based on the parameters in the automation I have set up in HomeKit.
**Logs:**

I really have none.

Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
I am not sure what this is…I have HOOBs.

**Screenshots:**


**Environment:**

* **Plugin Version**: latest
* **Homebridge Version**: <!-- homebridge -V --> HOOBs 
* **Node.js Version**: <!-- node -v -->
* **NPM Version**: <!-- npm -v -->
* **Operating System**: <!-- Raspbian / Ubuntu / Debian / Windows / macOS / Docker / hb-service --> Using my ipad to make automations

<!-- Click the "Preview" tab before you submit to ensure the formatting is correct. -->

**Comment by Githubnewbynewb** [comment]
Actually have some logs now. Not sure if they matter but here you go:
12/6/2022, 6:07:57 PMHOOBSDaikin One+Loading accessory from cache: Dining Room Thermostat
12/6/2022, 6:07:57 PMHOOBSDaikin One+Loading accessory from cache: Dining Room Outdoor Humidity
12/6/2022, 6:07:57 PMHOOBSDaikin One+Loading accessory from cache: Dining Room Indoor Humidity
12/6/2022, 6:07:57 PMHOOBSDaikin One+Loading accessory from cache: Dining Room Away State
12/6/2022, 6:07:57 PMHOOBSDaikin One+Loading accessory from cache: Dining Room Outdoor AQI
12/6/2022, 6:08:08 PMHOOBSDaikin One+Found 1 device(s):  []
12/6/2022, 6:08:08 PMHOOBSDaikin One+Device: Dining Room []
12/6/2022, 6:08:08 PMHOOBSDaikin One+Loaded initial data. []
12/6/2022, 6:08:08 PMHOOBSDaikin One+Found device: Dining Room
12/6/2022, 6:08:09 PMHOOBSDaikin One+Checking for thermostat...
12/6/2022, 6:08:09 PMHOOBSDaikin One+Restoring existing thermostat from cache: Dining Room Thermostat
12/6/2022, 6:08:09 PMHOOBSDaikin One+Checking for outdoor humidity sensor...
12/6/2022, 6:08:09 PMHOOBSDaikin One+Restoring existing outdoor humidity sensor from cache: Dining Room Outdoor Humidity
12/6/2022, 6:08:09 PMHOOBSDaikin One+Checking for indoor humidity sensor...
12/6/2022, 6:08:09 PMHOOBSDaikin One+Restoring existing indoor humidity sensor from cache: Dining Room Indoor Humidity
12/6/2022, 6:08:09 PMHOOBSDaikin One+Checking for outdoor Air Quality sensor...
12/6/2022, 6:08:09 PMHOOBSDaikin One+Restoring existing outdoor Air Quality sensor from cache: Dining Room Outdoor AQI
12/6/2022, 6:08:09 PMHOOBSDaikin One+Checking for indoor Air Quality sensor...
12/6/2022, 6:08:09 PMHOOBSDaikin One+Checking for Schedule Switch...
12/6/2022, 6:08:09 PMHOOBSDaikin One+Checking for Away Switch...
12/6/2022, 6:08:09 PMHOOBSDaikin One+Restoring existing away switch from cache: Dining Room Away State
12/6/2022, 6:08:09 PMHOOBSDaikin One+Checking for Emergency Heat Switch...
12/6/2022, 6:08:09 PMHOOBSDaikin One+Checking for One Clean Fan...
12/6/2022, 6:08:09 PMHOOBSDaikin One+Checking for Circulate Air Fan...

**Comment by jeffschubert** [comment]
@Githubnewbynewb I finally had a free evening to dig into this. Was able to get it working in most cases. The only case still outstanding is if the thermostat is off and your automation sets the temp along with turning it on. Specifically if the desired temp is different than when the thermostat was last in the state your automation is going to.
For example:
* Thermostat is set to Heat at 70*.
* You turn it off for whatever reason.
* Automation triggers to turn it to Heat at 72*.
* Result will be it is turned on to Heat at 70*. The desired 72* is lost.

If you're just changing temps and not going from Off to On, it seems to be just fine now.
