### ISSUE TITLE
Temp seating in Auto Mode

### ISSUE THREAD

**Issue by Githubnewbynewb** [jeffschubert/homebridge-daikin-oneplus#31]
**Describe Your Problem:**
Hello, first and foremost this has been a great plugin, so thank you for your work and effort on this project.  My issue is that this plugin works awesome when I have had the heat set for automations, for example set heat to 67 at 7AM, 62 at 11PM, etc.  Flawless.  However, I am now at the weird stage of our states weather where I need the thermostat in auto mode—dont let it get below 62 or over 73, for example, where the heat will kick on for the former and the AC for that latter.  What I am finding is that the auto mode does not stick.  If at 7AM I have it set to stay between 62 and 74, that usually works, but when at a specified time I ask it to now stay between 67-73, that setting doesn’t seem to stick.  It’s entirely possible I am doing something wrong.  I am a HOOBs user so I some knowledge about what I am doing but probably not enough to be too dangerous.  I did not send many screen shots, but I an if needed.  Basically the plugin is not passing to the thermostat my changes in the auto mode settings.

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json

"platform": "DaikinOnePlus",
    "name": "Daikin One+",
    "refreshInterval": 10,
    "user": "my username ",
    "password": "my password ",
    "includeDeviceName": true,
    "enableAwaySwitch": true

```
![IMG_5196](https://user-images.githubusercontent.com/92611778/233799266-9c54b262-e5cb-4107-90e7-0730dd698ca6.png)

**Screenshots:**

**Environment:**

3.1.2
* **Homebridge Version**: <HOOBs 4.3.0>
* **Node.js Version**: <I am not sure what this is>
* **NPM Version**: <I am not sure what this is>
* **Operating System**: <This happens on all my iOS devices>

**Comment by jeffschubert** [comment]
@Githubnewbynewb This sounds a lot like #29. The automation will send a series of requests. I'm betting it is effectively telling the plugin to switch to auto (even if already there), then change temp, etc. But as noted in the other thread, they end up overwriting each other. I'm thinking I'll have to rewrite a bit of the logic so it essentially buffers a series of requests and then makes one API call to the thermostat to set everything at once. That's a bigger undertaking so it might be a while before I can dedicate time to it.

**Comment by Githubnewbynewb** [comment]
Thanks @jeffschubert. Appreciate the update.

**Comment by jeffschubert** [comment]
@Githubnewbynewb I've made some changes for the next release that will fix setting the threshold temps when changing to auto mode or otherwise changing either of the thresholds. As I suspected, I'm having to bundle the threshold requests and send them together.

**Comment by Githubnewbynewb** [comment]
Jeff, I was just thinking about this yesterday. Thanks very much. I’ll look for the new update.

**Comment by Githubnewbynewb** [comment]
👍🏻 Thank you
