### ISSUE TITLE
Indoor Air Quality Sensor.

### ISSUE THREAD

**Issue by teddy99525** [jeffschubert/homebridge-daikin-oneplus#34]
Notice that the plugin is not displaying the Indoor Air Quality Sensor information.
It will display the outdoor when active. 
 
![Screenshot 2023-06-10 at 10 38 22 AM](https://github.com/jeffschubert/homebridge-daikin-oneplus/assets/97484857/4e04ef6f-f0dd-43e6-97ce-3a313ef0f103)

![IMG_220B65F24CF3-1](https://github.com/jeffschubert/homebridge-daikin-oneplus/assets/97484857/e0abf58c-2724-4158-a1f3-74bf33d12c27)

Environment:
Plugin Version: 3.1.2
Homebridge Version:1.6.1
Node.js Version: 18.12.1
Operating System: Raspbain

**Comment by jeffschubert** [comment]
Mine doesn't show it either. But it may dependent upon your system having an indoor sensor. I'll confirm when I get a chance.

**Comment by jeffschubert** [comment]
A screenshot from the Daikin app seems to back that up for my thermostat. It only gives detailed outside AQI. Indoor is essentially just whether it thinks the filter is ok. Which, if I recall, is simply based on whether there's sufficient airflow being pulled through the filter. 
![image](https://github.com/jeffschubert/homebridge-daikin-oneplus/assets/45114865/21ceb9b8-fe68-4917-b628-086f8aec6640)
