### ISSUE TITLE
Can't locate plugin in Homebridge UI X for install

### ISSUE THREAD

**Issue by vaficionado** [jeffschubert/homebridge-daikin-oneplus#4]
Howdy! This may just be a simple clarification needed request for the `readme.md` but I'm unable to find this plugin to install via Homebridge UI X. Tried searching for "Daiken" and "DaikenOnePlus" and no luck.

Also tried via `npm -I homebridge-daikin-oneplus` and it couldn't be found there either. 

Just curious what the best way to get this installed would be. I've installed many other plugins and know my install is functional...

**Comment by jeffschubert** [comment]
Sorry, just now seeing this. It looks like you've got a typo. It is `Daikin` not `Daiken`. Search for `daikin-oneplus` and it should come right up:
![daikin-oneplus](https://user-images.githubusercontent.com/45114865/127956256-bcde45b4-a49f-49d1-87b8-e0883a9e69ce.png)

**Comment by jeffschubert** [comment]
Also thanks for pointing out the need for details in the `readme.md`. I've updated it accordingly.

**Comment by vaficionado** [comment]
LOL, well that certainly is embarrassing. Autocorrect seems to have bitten me on this one. I went back and made sure to enter the correct spelling and it did come up no problem. My mistake here, but thanks for the reply and the readme update!

**Comment by vaficionado** [comment]
I'll close this issue out, thanks for addressing - but I'm getting an error now, will open a new one for that 🙂
