### ISSUE TITLE
Fan speed control

### ISSUE THREAD

**Issue by JakeScheck** [jeffschubert/homebridge-daikin-oneplus#45]
Nice plugin, works great and fills the need of getting my Daikin One Touch into HomeKit.

In my thermostat under Settings, Fan, I have cooling fan speed and heating fan speed options. I normally leave these set to auto, but occasionally I control them manually. It would be great to have the option to set these within HomeKit as then I could automate this, or more quickly access it.

**Comment by snydema1** [comment]
I would love to see this too.  I typically need to run my fans in high during the day to keep the house cool, but try to drop them to auto at night when the high speed isn’t necessary.  

Thanks for all the work on this great plugin!

**Comment by jeffschubert** [comment]
@JakeScheck , @snydema1 Try the 'Circulate Air' fan accessory within the plugin. It gives you a slider that'll adjust between off and low/med/high. I admit I probably could have just named it 'Fan', but I tried to match how it was labeled in my Daikin App under the Air Quality tab.

**Comment by jeffschubert** [comment]
If that's not what you're looking for, feel free to reopen with more detail and I'll take a look.
